"""Parse BNGL text into a ReactionNetwork.

Handles the BNGL subset generated by INDRA's BnglAssembler and the manual
assembler in indra_assembly.py.  This is NOT a full BNGL parser — for that,
use an ANTLR4 grammar.  It covers:
  - begin/end parameter blocks
  - begin/end molecule types blocks
  - begin/end seed species blocks
  - begin/end reaction rules blocks (forward-only and reversible)
"""
from __future__ import annotations

import re
from typing import Dict, List, Optional, Tuple

from .site_graph import Protein, ReactionNetwork, Rule, Site


def bngl_to_reaction_network(
    bngl_text: str,
    metadata: Optional[Dict] = None,
) -> ReactionNetwork:
    """Parse a BNGL model string into a ReactionNetwork."""
    params = _parse_parameters(bngl_text)
    mol_types = _parse_molecule_types(bngl_text)
    initial_concentrations = _parse_seed_species(bngl_text)
    rules = _parse_reaction_rules(bngl_text, params)

    proteins: Dict[str, Protein] = {}
    for mol_name, sites_spec in mol_types.items():
        sites: List[Site] = []
        for sname, states in sites_spec:
            if states:
                stype = "modification"
            else:
                stype = "binding"
            sites.append(
                Site(
                    name=sname,
                    site_type=stype,
                    states=list(states),
                    allowed_partners=[],
                )
            )
        proteins[mol_name] = Protein(name=mol_name, sites=sites)

    # Infer allowed_partners from binding rules.
    for rule in rules:
        if rule.rule_type in ("binding", "unbinding"):
            if len(rule.reactants) == 2:
                a, b = rule.reactants[0], rule.reactants[1]
                # Strip BNGL pattern syntax to get bare molecule names.
                a_base = _bare_mol_name(a)
                b_base = _bare_mol_name(b)
                _add_partner(proteins, a_base, b_base)
                _add_partner(proteins, b_base, a_base)

    meta = dict(metadata or {})
    meta["initial_concentrations"] = initial_concentrations
    meta["bngl_parameters"] = params

    network = ReactionNetwork(proteins=proteins, rules=rules, metadata=meta)
    return network


# ── Block extraction ─────────────────────────────────────────────────


def _extract_block(text: str, block_name: str) -> str:
    pattern = re.compile(
        rf"begin\s+{block_name}\s*\n(.*?)end\s+{block_name}",
        re.DOTALL | re.IGNORECASE,
    )
    m = pattern.search(text)
    return m.group(1).strip() if m else ""


# ── Parameters ───────────────────────────────────────────────────────


def _parse_parameters(text: str) -> Dict[str, float]:
    block = _extract_block(text, "parameters")
    params: Dict[str, float] = {}
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) >= 2:
            try:
                params[parts[0]] = float(parts[1])
            except ValueError:
                continue
    return params


# ── Molecule types ───────────────────────────────────────────────────


def _parse_molecule_types(text: str) -> Dict[str, List[Tuple[str, List[str]]]]:
    """Parse molecule types block.

    Returns {mol_name: [(site_name, [state1, state2, ...]), ...]}.
    """
    block = _extract_block(text, "molecule types")
    mol_types: Dict[str, List[Tuple[str, List[str]]]] = {}
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        mol_name, sites = _parse_mol_pattern(line)
        if mol_name:
            mol_types[mol_name] = sites
    return mol_types


def _parse_mol_pattern(pattern: str) -> Tuple[str, List[Tuple[str, List[str]]]]:
    """Parse 'STAT3(Y705~u~p,SH2)' into ('STAT3', [('Y705', ['u','p']), ('SH2', [])])."""
    m = re.match(r"(\w+)\(([^)]*)\)", pattern.strip())
    if not m:
        # Bare molecule: 'STAT3' with no sites
        name = pattern.strip().split()[0] if pattern.strip() else ""
        return (name, []) if name else ("", [])

    mol_name = m.group(1)
    sites_str = m.group(2).strip()
    sites: List[Tuple[str, List[str]]] = []

    if not sites_str:
        return mol_name, sites

    for site_token in sites_str.split(","):
        site_token = site_token.strip()
        if not site_token:
            continue
        # Remove bond markers like !1, !+, !?
        site_token = re.sub(r"![^\s,)~]*", "", site_token)
        # Parse states: site_name~state1~state2
        parts = site_token.split("~")
        sname = parts[0].strip()
        states = [s.strip() for s in parts[1:] if s.strip()]
        if sname:
            sites.append((sname, states))

    return mol_name, sites


# ── Seed species ─────────────────────────────────────────────────────


def _parse_seed_species(text: str) -> Dict[str, float]:
    block = _extract_block(text, "seed species")
    concentrations: Dict[str, float] = {}
    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Format: MolPattern concentration
        # e.g., STAT3(Y705~u) 1.0
        parts = line.rsplit(None, 1)
        if len(parts) == 2:
            species_name = _state_qualified_name(parts[0].strip())
            try:
                concentrations[species_name] = float(parts[1])
            except ValueError:
                continue
    return concentrations


# ── Reaction rules ───────────────────────────────────────────────────


def _parse_reaction_rules(text: str, params: Dict[str, float]) -> List[Rule]:
    block = _extract_block(text, "reaction rules")
    rules: List[Rule] = []
    counter = 0

    for line in block.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue

        counter += 1

        # Strip optional rule label: "r1: ..."
        if ":" in line and not line.startswith("("):
            label_part, _, line = line.partition(":")
            rule_name = label_part.strip()
            line = line.strip()
        else:
            rule_name = f"rule_{counter}"

        # Detect reversible (<->) vs forward-only (->)
        if "<->" in line:
            lhs, _, rhs_and_rates = line.partition("<->")
            reversible = True
        elif "->" in line:
            lhs, _, rhs_and_rates = line.partition("->")
            reversible = False
        else:
            continue

        # Split RHS into products and rate(s)
        # Products end where the rate parameters begin (last 1 or 2 tokens).
        rhs_tokens = rhs_and_rates.strip().split()
        if not rhs_tokens:
            continue

        # Rate parameters are the rightmost tokens that look like numbers or param names.
        rate_tokens: List[str] = []
        product_tokens: List[str] = []
        # Walk backwards to find where rates start.
        # For reversible: "A().B() kf, kr" → rates = ["kf,", "kr"] or "kf", "kr"
        # For forward: "A().B() kf" → rates = ["kf"]
        found_plus = False
        for tok in reversed(rhs_tokens):
            tok_clean = tok.strip(",")
            if _is_rate_token(tok_clean, params):
                rate_tokens.insert(0, tok)
            else:
                product_tokens = rhs_tokens[: rhs_tokens.index(tok) + 1]
                break

        if not product_tokens:
            # All tokens were rates — the last non-rate must be a product
            product_tokens = rhs_tokens[:1]
            rate_tokens = rhs_tokens[1:]

        product_str = " ".join(product_tokens)

        reactant_mols = _extract_mol_names(lhs.strip())
        product_mols = _extract_mol_names(product_str)
        rates = _resolve_rates(rate_tokens, params)

        fwd_rate = rates[0] if rates else 0.01
        rule_type = _infer_rule_type(lhs.strip(), product_str, reactant_mols, product_mols)

        rules.append(
            Rule(
                name=rule_name,
                rule_type=rule_type,
                reactants=reactant_mols,
                products=product_mols,
                rate=fwd_rate,
            )
        )

        if reversible and len(rates) >= 2:
            rev_type = _reverse_rule_type(rule_type)
            rules.append(
                Rule(
                    name=f"{rule_name}_rev",
                    rule_type=rev_type,
                    reactants=product_mols,
                    products=reactant_mols,
                    rate=rates[1],
                )
            )

    return rules


# ── Helpers ──────────────────────────────────────────────────────────


def _bare_mol_name(pattern: str) -> str:
    """Extract the bare molecule name from a BNGL pattern like 'STAT3(Y705~u)'."""
    m = re.match(r"(\w+)", pattern.strip())
    return m.group(1) if m else pattern.strip()


def _extract_mol_names(expr: str) -> List[str]:
    """Extract state-qualified species names from a BNGL expression.

    'JAK1(activity~active) + STAT3(Y705~u)' → ['JAK1__activity_active', 'STAT3__Y705_u']
    'A(x!1).B(y!1)' → ['A:B'] (complex)
    'STAT3()' → ['STAT3']
    """
    tokens = re.split(r"\s*\+\s*", expr.strip())
    names: List[str] = []
    for tok in tokens:
        tok = tok.strip()
        if not tok:
            continue
        # Complex: A(x!1).B(y!1) → single complex species
        sub_mols = re.split(r"(?<=[)])\.", tok)
        if len(sub_mols) > 1:
            parts = [_state_qualified_name(s) for s in sub_mols]
            names.append(":".join(parts))
        else:
            name = _state_qualified_name(tok)
            if name and name not in ("0", "Trash"):
                names.append(name)
    return names


def _state_qualified_name(pattern: str) -> str:
    """Convert 'STAT3(Y705~u)' to 'STAT3__Y705_u', 'JAK1()' to 'JAK1'.

    Preserves state information so ODE has distinct variables per state.
    Ignores bond markers (!N, !+, !?).
    """
    pattern = pattern.strip()
    m = re.match(r"(\w+)\(([^)]*)\)", pattern)
    if not m:
        # Bare name or malformed
        return re.match(r"(\w+)", pattern).group(1) if re.match(r"(\w+)", pattern) else ""

    mol_name = m.group(1)
    sites_str = m.group(2).strip()

    if not sites_str:
        return mol_name

    # Extract state-bearing sites (ignore bonds for ODE species naming)
    state_parts = []
    for site_token in sites_str.split(","):
        site_token = site_token.strip()
        if not site_token:
            continue
        # Remove bond markers
        site_token = re.sub(r"![^\s,)~]*", "", site_token).strip()
        parts = site_token.split("~")
        if len(parts) >= 2:
            # Site with a specific state: Y705~u → Y705_u
            sname = parts[0].strip()
            sval = parts[1].strip()  # Take the first (current) state
            if sname and sval:
                state_parts.append(f"{sname}_{sval}")

    if state_parts:
        return f"{mol_name}__{'_'.join(sorted(state_parts))}"
    return mol_name


def _is_rate_token(tok: str, params: Dict[str, float]) -> bool:
    tok = tok.strip(",")
    if tok in params:
        return True
    try:
        float(tok)
        return True
    except ValueError:
        return False


def _resolve_rates(rate_tokens: List[str], params: Dict[str, float]) -> List[float]:
    rates: List[float] = []
    for tok in rate_tokens:
        for sub in tok.split(","):
            sub = sub.strip()
            if not sub:
                continue
            if sub in params:
                rates.append(params[sub])
            else:
                try:
                    rates.append(float(sub))
                except ValueError:
                    rates.append(0.01)
    return rates


def _infer_rule_type(
    lhs: str,
    rhs: str,
    reactant_names: List[str],
    product_names: List[str],
) -> str:
    """Heuristic rule type inference from BNGL patterns."""
    if "~u" in lhs and "~p" in rhs:
        return "phosphorylation"
    if "~p" in lhs and "~u" in rhs:
        return "dephosphorylation"
    if "~active" in lhs and "~inactive" in rhs:
        return "inhibition"
    if "~inactive" in lhs and "~active" in rhs:
        return "activation"
    if "!" in rhs and "!" not in lhs:
        return "binding"
    if "!" in lhs and "!" not in rhs:
        return "unbinding"
    if len(reactant_names) == 2 and len(product_names) == 2:
        return "catalysis"
    return "reaction"


def _reverse_rule_type(rule_type: str) -> str:
    _rev = {
        "binding": "unbinding",
        "unbinding": "binding",
        "phosphorylation": "dephosphorylation",
        "dephosphorylation": "phosphorylation",
        "inhibition": "activation",
        "activation": "inhibition",
    }
    return _rev.get(rule_type, "reaction")


def _add_partner(proteins: Dict[str, Protein], mol_name: str, partner: str) -> None:
    if mol_name not in proteins:
        return
    protein = proteins[mol_name]
    for site in protein.sites:
        if site.site_type == "binding" and partner not in site.allowed_partners:
            site.allowed_partners.append(partner)
            return
